# Generated by Django 4.2.3 on 2024-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('Service', models.TextField()),
            ],
        ),
    ]
