# Generated by Django 4.2.3 on 2024-07-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plumber',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='plumber',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='plumber',
            old_name='phone',
            new_name='Phone',
        ),
    ]
