# Generated by Django 4.2.3 on 2024-07-07 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_location_plumber_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumber',
            name='Datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plumber',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plumber',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='Service',
            field=models.TextField(max_length=100),
        ),
    ]
